import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { Flip, ToastContainer } from 'react-toastify'
import 'react-toastify/ReactToastify.css'

const roboto = Roboto({ weight: ['400', '500'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pixelvirt Traffic Surveillance',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <Navbar />
        <main>
          <ToastContainer transition={Flip} />
          {children}
        </main>
      </body>
    </html>
  )
}
